import disableAutofix from 'eslint-plugin-disable-autofix'
import globals from 'globals'
import html from '@html-eslint/eslint-plugin'
import htmlParser from '@html-eslint/parser'
import parser from '@typescript-eslint/parser'
import pluginJs from '@eslint/js'
import tsPlugin from '@typescript-eslint/eslint-plugin'

export default [
  // TS config
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser,
      parserOptions: {
        project: './tsconfig.json',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      '@typescript-eslint/stylistic': tsPlugin,
      '@typescript-eslint/strict-type-checked': tsPlugin,
    },
    rules: {
      '@typescript-eslint/array-type': 'warn',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/consistent-generic-constructors': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      '@typescript-eslint/init-declarations': 'warn',
      '@typescript-eslint/no-base-to-string': 'warn',
      '@typescript-eslint/no-confusing-non-null-assertion': 'error',
      '@typescript-eslint/no-confusing-void-expression': 'error',
      '@typescript-eslint/no-deprecated': 'warn',
      '@typescript-eslint/no-dupe-class-members': 'error',
      '@typescript-eslint/no-duplicate-enum-values': 'warn',
      '@typescript-eslint/no-duplicate-type-constituents': 'error',
      '@typescript-eslint/no-dynamic-delete': 'warn',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-extra-non-null-assertion': 'error',
      '@typescript-eslint/no-extraneous-class': 'warn',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-for-in-array': 'warn',
      '@typescript-eslint/no-implied-eval': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      // '@typescript-eslint/no-inferrable-types': 'warn',
      '@typescript-eslint/no-meaningless-void-operator': 'error',
      '@typescript-eslint/no-mixed-enums': 'warn',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'error',
      '@typescript-eslint/no-unnecessary-qualifier': 'error',
      '@typescript-eslint/no-unnecessary-template-expression': 'error',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
      '@typescript-eslint/no-useless-empty-export': 'error',
      '@typescript-eslint/no-wrapper-object-types': 'warn',
      '@typescript-eslint/prefer-enum-initializers': 'warn',
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/promise-function-async': 'error',
      '@typescript-eslint/prefer-for-of': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'error',
      '@typescript-eslint/unified-signatures': 'error',
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          checksSpreads: true,
          checksConditionals: true,
          checksVoidReturn: false,
        },
      ],
      '@typescript-eslint/max-params': [
        'warn',
        {
          countVoidThis: true,
          max: 5,
        },
      ],
      '@typescript-eslint/consistent-type-exports': [
        'warn',
        {
          fixMixedExportsWithInlineTypeSpecifier: true,
        },
      ],
      '@typescript-eslint/naming-convention': [
        'error',
        {
          selector: 'default',
          format: ['camelCase', 'PascalCase'],
        },
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE'],
          leadingUnderscore: 'allow',
        },
        {
          selector: 'variable',
          modifiers: ['const'],
          types: ['boolean', 'string', 'number', 'array'],
          format: ['UPPER_CASE'],
        },
        {
          selector: 'variable',
          modifiers: ['const'],
          types: ['function'],
          format: ['camelCase'],
        },
        {
          selector: 'function',
          format: ['camelCase'],
        },
        {
          selector: 'typeLike',
          format: ['PascalCase'],
        },
      ],
    },
  },
  // JS config
  {
    languageOptions: { globals: globals.browser },
    ...pluginJs.configs.recommended,
    rules: {
      eqeqeq: ['error', 'always'],
      quotes: ['warn', 'single'],
      camelcase: ['error', { ignoreImports: true }],
      /* eslint-disable-next-line no-magic-numbers */
      complexity: ['error', 7],
      curly: ['error', 'multi-line'],
      /* eslint-disable-next-line no-magic-numbers */
      'max-params': ['warn', 5],
      'for-direction': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-imports': 'error',
      'no-invalid-regexp': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',
      'no-console': 'warn',
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-shadow': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'default-case': 'error',
      'no-alert': 'warn',
      'no-bitwise': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-extra-label': 'error',
      'no-label-var': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-undef-init': 'error',
      'no-lone-blocks': 'warn',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'error',
      'no-else-return': 'error',
      'no-nested-ternary': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-rename': 'error',
      'operator-assignment': ['warn', 'always'],
      'require-await': 'error',
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-empty-function': ['error', { allow: ['setters', 'constructors'] }],
      'no-magic-numbers': [
        'warn',
        {
          ignore: [0, 1],
          ignoreArrayIndexes: true,
          ignoreDefaultValues: true,
          ignoreClassFieldInitialValues: true,
          detectObjects: false,
        },
      ],
      'sort-imports': [
        'error',
        {
          ignoreCase: false,
          ignoreDeclarationSort: false,
          ignoreMemberSort: false,
          memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
          allowSeparatedGroups: false,
        },
      ],
      'sort-vars': 'error',
      'vars-on-top': 'error',
    },
  },

  // HTML config
  {
    ...html.configs['flat/recommended'],
    files: ['**/*.html'],
    plugins: {
      '@html-eslint': html,
      'disable-autofix': disableAutofix,
    },
    rules: {
      '@html-eslint/require-attrs': [
        'error',
        {
          tag: 'img',
          attr: 'alt',
        },
        {
          tag: 'img',
          attr: 'src',
        },
        {
          tag: 'a',
          attr: 'href',
        },
      ],
      '@html-eslint/attrs-newline': 'off',
      'disable-autofix/@html-eslint/attrs-newline': [
        'warn',
        {
          closeStyle: 'newline',
          ifAttrsMoreThan: 3,
        },
      ],
      '@html-eslint/no-restricted-attr-values': [
        'error',
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: [
            '\\b(_{0,2})?(-{0,2})?([bB][oO][lL][dD]|[bB][oO][lL][dD][eE][rR]|[lL][iI][gG][hH]|[lL][iI][gG][hH][tT][eE][rR]|[nN][oO][rR][mM][aA][lL]|[iI][tT][aA][lL][iI][cC]|[oO][bB][lL][iI][qQ][uU][eE]|[uU][nN][dD][eE][rR][lL][iI][nN][eE]|[lL][iI][nN][eE]-[tT][hH][rR][oO][uU][gG][hH]|[oO][vV][eE][rR][lL][iI][nN][eE]|[wW][iI][dD][eE]|[nN][aA][rR][rR][oO][wW]|[tT][aA][lL][lL]|[sS][hH][oO][rR][tT]|[rR][eE][lL][aA][tT][iI][vV][eE]|[aA][bB][sS][oO][lL][uU][tT][eE]|[rR][eE][dD]|[bB][lL][uU][eE]|[gG][rR][eE][eE][nN]|[yY][eE][lL][lL][oO][wW]|[pP][uU][rR][pP][lL][eE]|[oO][rR][aA][nN][gG][eE]|[pP][iI][nN][kK]|[bB][lL][aA][cC][kK]|[wW][hH][iI][tT][eE]|[gG][rR][aA][yY]|[lL][iI][gG][hH][tT][gG][rR][aA][yY]|[dD][aA][rR][kK][gG][rR][aA][yY]|[bB][rR][oO][wW][nN]|[cC][yY][aA][nN]|[mM][aA][gG][eE][nN][tT][aA])(_{0,2})?(-{0,2})?\\b',
          ],
          // attrValuePatterns: [
          //   '\\b(_{0,2})?(-{0,2})?(bold|Bold|BOLD|bolder|BOLDER|Bolder|ligh|LIGHT|Light|lighter|LIGHTER|Lighter|normal|NORMAL|Normal|italic|ITALIC|Italic|oblique|OBLIQUE|Oblique|underline|UNDERLINE|Underline|line-through|LINE-THROUGH|Line-through|overline|OVERLINE|Overline|wide|WIDE|Wide|narrow|NARROW|Narrow|tall|TALL|Tall|short|SHORT|Short|relative|RELATIVE|Relative|absolute|ABSOLUTE|Absolute|red|RED|Red|blue|BLUE|Blue|green|GREEN|Green|yellow|YELLOW|Yellow|purple|PURPLE|Purple|orange|ORANGE|Orange|pink|PINK|Pink|black|BLACK|Black|white|WHITE|White|gray|GRAY|Gray|lightgray|LIGHTGRAY|Lightgray|darkgray|DARKGRAY|Darkgray|brown|BROWN|Brown|cyan|CYAN|Cyan|magenta|MAGENTA|Magenta)(_{0,2})?(-{0,2})?\\b',
          // ],
          message: 'One of the ClassName is in restricted list',
        },
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: [
            '[a-zA-Z\\d]+(_{3,}|-{3,})',
            '(_|-)$',
            '[a-zA-Z\\d]*(_|-)$',
            '[a-zA-Z\\d][-]?[a-zA-Z\\d]+(_|-{2})[-a-zA-Z\\d]+(_|-{2})',
            '[a-zA-Z\\d]+(__)[-a-zA-Z]+(__)',
            '[^a-zA-Z\\d_\\-\\s\\{\\}\\/#]',
            '\\{\\{[-_]*\\}\\}',
            '\\{\\}|\\{\\{\\}\\}',
            '\\{[^\\}]*$',
            '(?<![a-zA-Z0-9\\}])\\}',
            '(?<!\\{)#',
            '(?<!\\{)\\/',
          ],
          message: 'Class pattern must match BEM',
        },
        // {
        //   attrPatterns: ['^class$'],
        //   attrValuePatterns: ['(?<!_)_(?!_)'],
        //   message: 'using wrong modificator syntaxis. instead -- you use _',
        // },
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: ['[a-zA-Z]+--[a-zA-Z]+'],
          message: 'using wrong modificator syntaxis. instead _ you use --',
        },
        {
          attrPatterns: ['^id$'],
          attrValuePatterns: ['[^a-zA-Z\\d_\\-\\s\\{\\}]'],
          message: 'Incorrect ID pattern',
        },
      ],
      '@html-eslint/element-newline': [
        'error',
        {
          skip: ['p', 'span'],
        },
      ],
      '@html-eslint/no-extra-spacing-attrs': ['error', { disallowMissing: true }],
      '@html-eslint/no-multiple-empty-lines': ['error', { max: 1 }],
      '@html-eslint/no-target-blank': 'warn',
      '@html-eslint/no-duplicate-attrs': 'error',
      '@html-eslint/no-duplicate-id': 'error',
      '@html-eslint/no-inline-styles': 'warn',
      '@html-eslint/no-obsolete-tags': 'error',
      '@html-eslint/no-script-style-type': 'error',
      '@html-eslint/require-button-type': 'warn',
      '@html-eslint/require-closing-tags': 'error',
      '@html-eslint/require-doctype': 'error',
      '@html-eslint/require-li-container': 'error',
      '@html-eslint/no-multiple-h1': 'error',
      '@html-eslint/no-skip-heading-levels': 'error',
      '@html-eslint/require-lang': 'warn',
      '@html-eslint/require-meta-charset': 'error',
      '@html-eslint/require-meta-description': 'error',
      '@html-eslint/require-title': 'error',
      '@html-eslint/require-img-alt': 'error',
      '@html-eslint/lowercase': 'error',
      '@html-eslint/no-positive-tabindex': 'error',
      '@html-eslint/no-non-scalable-viewport': 'warn',
      // '@html-eslint/id-naming-convention': ['warn', 'camelCase'],
      '@html-eslint/sort-attrs': 'off',
      'disable-autofix/@html-eslint/sort-attrs': [
        'warn',
        {
          priority: [
            'action',
            'rel',
            'type',
            'src',
            'href',
            'target',
            'srcset',
            'media',
            'alt',
            'class',
            'id',
            'name',
            'content',
            'accept',
            'width',
            'height',
            'style',
          ],
        },
      ],
    },
    languageOptions: {
      parser: htmlParser,
    },
  },
]
